-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 20:00:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projektPwl_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projektPwl_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektPwl_DB` DEFAULT CHARACTER SET utf8 ;
USE `projektPwl_DB` ;

-- -----------------------------------------------------
-- Table `projektPwl_DB`.`Uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektPwl_DB`.`Uzytkownik` (
  `id_uzytkownik` INT NOT NULL AUTO_INCREMENT,
  `typ_uzytkownik` INT NOT NULL,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `pass_SHA-512` CHAR(128) NOT NULL,
  PRIMARY KEY (`id_uzytkownik`),
  UNIQUE INDEX `id_uzytkownik_UNIQUE` (`id_uzytkownik` ASC) VISIBLE,
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektPwl_DB`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektPwl_DB`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(255) NOT NULL,
  `image_dir` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_image`),
  UNIQUE INDEX `id_image_UNIQUE` (`id_image` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektPwl_DB`.`Okazja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektPwl_DB`.`Okazja` (
  `id_okazja` INT NOT NULL AUTO_INCREMENT,
  `id_uzytkownik` INT NOT NULL,
  `id_image` INT NOT NULL,
  `cena_okazja` INT NULL,
  `tytul_okazja` VARCHAR(45) NULL,
  `opis_okazja` VARCHAR(45) NULL,
  `link_okazja` VARCHAR(45) NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_okazja`),
  UNIQUE INDEX `id_okazja_UNIQUE` (`id_okazja` ASC) VISIBLE,
  INDEX `fk_Okazja_Uzytkownik_idx` (`id_uzytkownik` ASC) VISIBLE,
  INDEX `fk_Okazja_images1_idx` (`id_image` ASC) VISIBLE,
  CONSTRAINT `fk_Okazja_Uzytkownik`
    FOREIGN KEY (`id_uzytkownik`)
    REFERENCES `projektPwl_DB`.`Uzytkownik` (`id_uzytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Okazja_images1`
    FOREIGN KEY (`id_image`)
    REFERENCES `projektPwl_DB`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektPwl_DB`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektPwl_DB`.`comment` (
  `id_comment` INT NOT NULL,
  `id_okazja` INT NOT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_Okazja1_idx` (`id_okazja` ASC) VISIBLE,
  CONSTRAINT `fk_comment_Okazja1`
    FOREIGN KEY (`id_okazja`)
    REFERENCES `projektPwl_DB`.`Okazja` (`id_okazja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektPwl_DB`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektPwl_DB`.`like` (
  `id_like` INT NOT NULL,
  `ileLike` INT NULL,
  `id_okazja` INT NOT NULL,
  PRIMARY KEY (`id_like`),
  INDEX `fk_like_Okazja1_idx` (`id_okazja` ASC) VISIBLE,
  CONSTRAINT `fk_like_Okazja1`
    FOREIGN KEY (`id_okazja`)
    REFERENCES `projektPwl_DB`.`Okazja` (`id_okazja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `projektPwl_DB`.`Uzytkownik`
-- -----------------------------------------------------
START TRANSACTION;
USE `projektPwl_DB`;
INSERT INTO `projektPwl_DB`.`Uzytkownik` (`id_uzytkownik`, `typ_uzytkownik`, `imie`, `nazwisko`, `e_mail`, `login`, `pass_SHA-512`) VALUES (001, 1, 'Daniel', 'Dmitruk', 'danql1996@gmail.com', 'admin', 'b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86');
INSERT INTO `projektPwl_DB`.`Uzytkownik` (`id_uzytkownik`, `typ_uzytkownik`, `imie`, `nazwisko`, `e_mail`, `login`, `pass_SHA-512`) VALUES (002, 0, 'Jan', 'Kowalski', 'email1@wp.pl', 'login1', 'b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86');
INSERT INTO `projektPwl_DB`.`Uzytkownik` (`id_uzytkownik`, `typ_uzytkownik`, `imie`, `nazwisko`, `e_mail`, `login`, `pass_SHA-512`) VALUES (003, 0, 'Stanisław', 'Kret', 'email2@wp.pl', 'login2', 'b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86');
INSERT INTO `projektPwl_DB`.`Uzytkownik` (`id_uzytkownik`, `typ_uzytkownik`, `imie`, `nazwisko`, `e_mail`, `login`, `pass_SHA-512`) VALUES (004, 0, 'Maciej', 'Bąk', 'email3@wp.pl', 'login3', 'b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projektPwl_DB`.`images`
-- -----------------------------------------------------
START TRANSACTION;
USE `projektPwl_DB`;
INSERT INTO `projektPwl_DB`.`images` (`id_image`, `nazwa`, `image_dir`) VALUES (01, 'banany', 'https://static.pepper.pl/live_pl/threads/thread_large/default/245526_1.jpg');
INSERT INTO `projektPwl_DB`.`images` (`id_image`, `nazwa`, `image_dir`) VALUES (02, 'roidmi3s', 'https://static.pepper.pl/live_pl/threads/thread_large/default/245786_1.jpg');
INSERT INTO `projektPwl_DB`.`images` (`id_image`, `nazwa`, `image_dir`) VALUES (03, 'tymbark', 'https://static.pepper.pl/live_pl/threads/thread_large/default/246394_1.jpg');
INSERT INTO `projektPwl_DB`.`images` (`id_image`, `nazwa`, `image_dir`) VALUES (04, 'motorola', 'https://static.pepper.pl/live_pl/threads/thread_large/default/246272_1.jpg');
INSERT INTO `projektPwl_DB`.`images` (`id_image`, `nazwa`, `image_dir`) VALUES (05, 'dell', 'https://static.pepper.pl/live_pl/threads/thread_large/default/246454_1.jpg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projektPwl_DB`.`Okazja`
-- -----------------------------------------------------
START TRANSACTION;
USE `projektPwl_DB`;
INSERT INTO `projektPwl_DB`.`Okazja` (`id_okazja`, `id_uzytkownik`, `id_image`, `cena_okazja`, `tytul_okazja`, `opis_okazja`, `link_okazja`, `data`) VALUES (01, 002, 01, 2,99, 'Banany,cena za 1 kg@ Polomarket 27.03', 'Witam. W piątek 27.03 promocja w Polomarket na banany. Za 1 kg zapłacimy tylko 2,99', NULL, '2020-03-25');
INSERT INTO `projektPwl_DB`.`Okazja` (`id_okazja`, `id_uzytkownik`, `id_image`, `cena_okazja`, `tytul_okazja`, `opis_okazja`, `link_okazja`, `data`) VALUES (02, 002, 02, 42,50, 'Ładowarka samochodowa z Bluetooth Xiaomi ROIDMI 3S @DHgate', 'Ładowarka samochodowa Bluetooth Xiaomi ROIDMI 3S za $9,99.', 'https://www.dhgate.com/store/product/new-xiaomi-roidmi-3s-bluetooth-car-charger/505567288.html?f=bda%7Ccontent%7Cpepperpl%7Cdeals&utm_medium=content&utm_source=pepperpldeals', '2020-03-24');
INSERT INTO `projektPwl_DB`.`Okazja` (`id_okazja`, `id_uzytkownik`, `id_image`, `cena_okazja`, `tytul_okazja`, `opis_okazja`, `link_okazja`, `data`) VALUES (03, 003, 03, 1,99, 'Tymbark 1,75 L przy zakupie 3 szt 1,99 zł Biedronka', 'W biedronce od dziś napój Tymbark 1,75 L w cenie 1,99 zł przy zakupie 3 szt.', NULL, '2020-03-26');
INSERT INTO `projektPwl_DB`.`Okazja` (`id_okazja`, `id_uzytkownik`, `id_image`, `cena_okazja`, `tytul_okazja`, `opis_okazja`, `link_okazja`, `data`) VALUES (04, 004, 04, 599, 'Motorola G7 Power (fioletowy - rzadki w promocjach) bateria 5000 mAh, pełny Dual SIM, 4/64, czysty Android. Smartfon z OleOle i RTV Euro AGD', 'Smartfon z czystym Androidem i bardzo dużą baterią, nie do rozładowania w jeden dzień nawet dla bardzo \"się starających\" (średnie lub lżejsze użytkowanie to nawet kilka dni bez ładowania, z uwagi na dodatkowo energooszczędny procesor).', 'https://www.oleole.pl/telefony-komorkowe/motorola-smartfon-moto-g7-power-4-64gb-ds-i-viol.bhtml?utm_source=2381265%7Cdigidip+PL&utm_medium=TradeDoubler&utm_campaign=%28TradeDoubler%29&utm_content=%2F', '2020-03-26');
INSERT INTO `projektPwl_DB`.`Okazja` (`id_okazja`, `id_uzytkownik`, `id_image`, `cena_okazja`, `tytul_okazja`, `opis_okazja`, `link_okazja`, `data`) VALUES (05, 004, 05, 409, 'Dell E7240 i5 4GB 128 SSD HDMI Win10 Pro (poleasingowe)', 'Jako że nie załapałem się na ostatnią okazję na HP 820 G1 z morele a nie dodają kolejnych sztuk póki co to szukałem alternatywy. Postanowiłem się z Wami podzielić okazją, którą znalazłem. Myślę, że jak za taką cenę do prac biurowych jest spoko. Cena niższa niż poleasingowych sztuk hp 820 g1 na morele, a parametry zbliżone. Ramu ma 4 mniej ale za niewielką dopłatą można dołożyć, laptop ma 1 wolny slot. Moją sztukę już dostałem jest z bonusem bo i7 zamiast i5, bateria 5h. Pare rysek i wgniotka na zewnątrz ale w środku jak nówka. Gwarancja 6 mies. Polecam.', 'https://allegro.pl/oferta/biznesowy-dell-e7240-i5-4gb-128-ssd-hdmi-win10-pro-8846004941?utm_source=tdb&utm_medium=afiliacja&utm_content=digidip+PL&tduid=217a93a390b5043bf1b56a9880315993', '2020-03-26');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projektPwl_DB`.`comment`
-- -----------------------------------------------------
START TRANSACTION;
USE `projektPwl_DB`;
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (001, 01, 'Zaiste zacna cena jak na Polo');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (002, 02, 'Mam od dawna i polecam. Najlepszy transmiter jaki jest. Naprawdę bardzo dobra jakość dźwięku jak na takie urządzenie. Jako ładowarka też daje radę. Ładnie ładuje 2.4A.');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (003, 02, 'Ja wolę jednak Baseusa, nie wywala bezpieczników, dźwięk jest lepszy i głośniejszy do tego ładowanie qc4. Trzy porty USB.');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (004, 02, 'Mam od kilkunastu miesięcy, z czystym sumieniem polecam.');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (005, 03, 'I to jest dobra cena, A nie jak w Żabce dwupak wychodzi 4,80 zł za sztukę');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (006, 04, 'Lajk za fioletowy');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (007, 05, 'Takie tanie gnojki mają Windows 10 Pro a te drozsze tylko Home, dziwneee');
INSERT INTO `projektPwl_DB`.`comment` (`id_comment`, `id_okazja`, `content`) VALUES (008, 05, 'Jak zawiasy w tym modelu ? Po wpadce jaką zrobiłem kupując Samsunga np535u3c zawiasy są równie ważne dla mnie co ekran laptopa.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projektPwl_DB`.`like`
-- -----------------------------------------------------
START TRANSACTION;
USE `projektPwl_DB`;
INSERT INTO `projektPwl_DB`.`like` (`id_like`, `ileLike`, `id_okazja`) VALUES (01, 10, 01);
INSERT INTO `projektPwl_DB`.`like` (`id_like`, `ileLike`, `id_okazja`) VALUES (02, 44, 02);
INSERT INTO `projektPwl_DB`.`like` (`id_like`, `ileLike`, `id_okazja`) VALUES (03, 13, 03);
INSERT INTO `projektPwl_DB`.`like` (`id_like`, `ileLike`, `id_okazja`) VALUES (04, 570, 04);
INSERT INTO `projektPwl_DB`.`like` (`id_like`, `ileLike`, `id_okazja`) VALUES (05, 120, 05);

COMMIT;

